version: "3.5"

services: 
    api-server:
        container_name: node-api-container
        restart: always
        build: .
        ports:
          - "5000:3000"
        links: 
          - mongoDB
        volumes: 
          - ./../:/usr/src/app
    mongo:
        container_name: mongoDataBase
        image: mongo
        ports:
          - "27017:27017"
        logging: 
          driver: none