version: "3.5"

services: 
    api-server:
        container_name: node-api-container
        restart: always
        build: .
        ports:
          - "${API_PORTS}"
        depends_on:
          - mongo
        links: 
          - mongo
        volumes: 
          - .:/workspace
    mongo:
        container_name: mongoDataBase
        image: mongo:4.0-xenial
        environment:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
          - "${MONGO_PORTS}"
        volumes:
          - ${MONGO_VOLUME}:/data/db